export { default as Home } from './Home';
export { default as MainContent } from './MainContent';
export { default as BuyNow} from './BuyNow';
export { default as AboutPage } from './AboutPage';
export { default as ContactPage } from './ContactPage';
export { default as Cart } from './Cart';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Checkout } from './Checkout';
export { default as PageNotFound404Error } from './PageNotFound404Error';
export { default as Profile } from './Profile';
export { default as ThankYou } from './ThankYou';
export { default as Success } from './Success';